version: 2
jobs:
    macos:
        macos:
            xcode: "9.0"
        steps:
            - checkout
            - run: swift test --parallel
    linux:
        docker:
            - image: norionomura/swift:40
        steps:
            - checkout
            - run: swift test --parallel
workflows:
    version: 2
    tests:
        jobs:
            - linux
